name: Meshery-extension Tests on Pull Request
on: [repository_dispatch]

jobs:
  build-ui-and-server:
    if: github.event.action == 'dispatch-pr-test'
    uses: layer5labs/meshery-extensions-packages/.github/workflows/extension-test-on-pr.yml@master
    with: 
      branch_name: ${{ github.event.client_payload.branch_name }}
      pr_number: ${{ github.event.client_payload.pr_number }} 
    secrets: 
      PROVIDER_TOKEN: ${{ secrets.PROVIDER_TOKEN }}
      NODE_VERSION: ${{ secrets.NODE_VERSION }}
      GO_VERSION: ${{ secrets.GO_VERSION }}
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  meshery-cloud-deploy:
    if: github.event.action == 'meshery-cloud-deploy'
    uses: layer5labs/meshery-extensions-packages/.github/workflows/meshery-cloud-release.yml@master
    with: 
      call-release-environment: ${{ github.event.client_payload.release_environment }}
      call-release-version: ${{ github.event.client_payload.release_version}} 
    secrets: 
      GLOBAL_TOKEN: ${{ secrets.GLOBAL_TOKEN }}