name: Notify Email
on: 
  workflow_dispatch:
    inputs:
      to:
        description: 'recipient'
        required: false
      # revision:
      #   description: 'Revision of release'
      #   required: true
jobs:
  email:
    name: Prepare email
    runs-on: "ubuntu-latest"
    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          # Required mail server address:
          server_address: smtp.gmail.com
          # Required mail server port:
          server_port: 465
          # Optional (recommended): mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: Github Actions job result
          # Required recipients' addresses:
          to: lee.calcote@layer5.io
          # Required sender full name (address can be skipped):
          from: L5io Release Manager # <user@example.com>
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional plain body:
          body: Build job of ${{github.repository}} completed successfully!
          # Optional HTML body read from file:
          html_body: '
            <html>
            <style>
                .container {
                  height: 200px;
                  position: relative;
                  border: 3px solid green;
                }

                .center {
                  margin: 0;
                  position: absolute;
                  top: 50%;
                  left: 50%;
                  width:70%;
                  -ms-transform: translate(-50%, -50%);
                  transform: translate(-50%, -50%);
                }
                </style>
        <body style="
        background: linear-gradient(122.25deg, #00B39F -2.45%, #195E4A 52.7%, #00B352 96.5%);
        border-radius: 10px 10px 0px 0px;">
        </body>
        </html>'
          # Optional carbon copy recipients:
          cc: leecalcote@icloud.com
          # Optional blind carbon copy  recipients:
          # bcc: r2d2@example.com,hansolo@example.com
          # Optional recipient of the email response:
          reply_to: no-reply@layer5.io
          # Optional unsigned/invalid certificates allowance:
          ignore_cert: true
          # Optional converting Markdown to HTML (set content_type to text/html too):
          convert_markdown: true
          # Optional attachments:
          attachments: attachments.zip,git.diff,./dist/static/*.js
          # Optional priority: 'high', 'normal' (default) or 'low'
          priority: low

