name: Publish Assets
on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to be released'
        required: true
        default: 'stale'

jobs:
  release:
    name: publish assets
    strategy:
      max-parallel: 10
      matrix:
        os: ["ubuntu-18.04"]
        include:
          - os: "ubuntu-18.04"
            distro: "meshery"
    runs-on: ${{ matrix.os }}
    steps:
    - name: pull packages
      run: |
        asset_id=$(curl -H "Authorization: token ${{ secrets.GLOBAL_TOKEN}}" "https://api.github.com/repos/layer5labs/meshery-extensions/releases" | jq -r '.[] | select(.tag_name == "${{ github.event.inputs.version }}")' | jq -r .assets | jq -r '.[] | select(.name == "provider-${{ matrix.distro }}.tar.gz")' | jq -r .id)
        echo $asset_id
        wget  --auth-no-challenge --header='Accept:application/octet-stream' https://${{ secrets.GLOBAL_TOKEN }}:@api.github.com/repos/layer5labs/meshery-extensions/releases/assets/$asset_id -O provider-${{ matrix.distro }}.tar.gz
    - name: publish
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GLOBAL_TOKEN }}
        tag:  ${{ github.event.inputs.version }}
        name: Meshery Extensions ${{ github.event.inputs.version }}
        allowUpdates: true
        artifactErrorsFailBuild: true
        artifacts: provider-${{ matrix.distro }}.tar.gz
        omitNameDuringUpdate: true
        replacesArtifacts: true
