name: Synthetic Tests
on: 
  schedule: 
    - cron: "15 * * * *"
jobs:
  test: 
    name: Test for Hydra, Kratos and Courier Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Run test
        run: |
          cd test
          go build -ldflags="-X 'main.kratosDbUrl=${{ secrets.MESHERY_CLOUD_AWS_KRAOTS_PROD_DB }}' -X 'main.monitorAccount=monitoring@layer5.io' -X 'main.alertAccount=support@layer5.io' -X  'main.smtpHost=${{ secrets.SMTP_HOST }}' -X 'main.smtpPort=${{ secrets.SMTP_PORT }}' -X 'main.smtpUsername=${{ secrets.MAIL_USERNAME }}' -X 'main.smtpPassword=${{ secrets.MAIL_PASSWORD }}' -X 'main.kratosPublicUrl=https://meshery.layer5.io/kratos' -X 'main.hydraPublicUrl=https://meshery.layer5.io/hydra'"  -a -o synthetic-test main.go
          ./synthetic-test
